export const appCopy = {
  productName: 'Brainova',
  productTagline: 'Aptitude testing with defensible analytics.',
  nav: {
    dashboard: 'Dashboard',
    tests: 'Tests',
    results: 'Results',
    admin: 'Admin',
    login: 'Sign in',
    signup: 'Sign up',
  },
  auth: {
    loginTitle: 'Welcome back',
    loginSubtitle: 'Enter your details to continue.',
    signupTitle: 'Create your account',
    signupSubtitle: 'Register with your admission number to start taking tests.',
    signOut: 'Sign out',
  },
  notFound: {
    eyebrow: '404',
    title: 'Page not found',
    body: "The page you're looking for doesn't exist.",
    action: 'Go home',
  },
  footer: 'Built for secure, server-scored aptitude testing.',
  upcoming: {
    tests: { title: 'Tests', body: '' },
    results: { title: 'Results', body: '' },
    admin: { title: 'Admin', body: '' },
  },
  testsPreview: {
    eyebrow: '',
    title: '',
    subtitle: '',
    loading: 'Loading…',
    errorTitle: 'Unable to load',
    emptyTitle: 'No questions found',
    emptyBody: '',
    questionsLabel: 'Questions',
    domainsLabel: 'Domains',
    attemptLabel: 'Suggested attempt',
    attemptValue: '25 min',
    relatedEyebrow: '',
    relatedTitle: '',
    questionBankLabel: 'Question bank',
    domainsAriaLabel: 'Domains',
    questionPrefix: 'Q',
    studyFocus: [] as string[],
  },
} as const;
